settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: simple-web-go
  path: .
  commands: 
    install:
      status: true
      method: go build -o tmp/simple-web-go.out main.go
    run:
      status: true
      method: tmp/simple-web-go.out
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
